name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run the build.sh scripts
      run: |
            # find the build.sh scripts and execute them
            echo "Running all build.sh scripts in repo"
            path=$(pwd)
            for f in $(find . -iname 'build.sh')
            do
              echo "Running $f"
              (cd $(dirname $f) && ./build.sh && cd $path) || (echo $f "Failed" && exit 1)
              echo "$f completed"
            done
            echo "Done running build.sh scripts"
